<?php

/**
 * Implements hook_menu().
 * Approve level settings/PR roles involved
 */
function camplus_pr_menu() {
	$items = array();
  $items['admin/config/camplus'] = array(
    'title' => 'Education Groupware',
    'position' => 'left',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/camplus/pr_settings'] = array(
    'title' => t('PR settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'camplus_pr.pages.inc',
  );
  $items['admin/config/camplus/pr_settings/rang_count'] = array(
    'title' => t('PR settings rang count'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' =>-28,
  );
	$items['admin/config/camplus/pr_settings/roles_involved'] = array(
		'title' => t('PR roles involved'),
		'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_roles_involved_settings_form'),
    'access arguments' => array('access administration pages'),
		'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-30,
	);
  $items['admin/config/camplus/pr_settings/roles_weight'] = array(
    'title' => t('PR roles weight'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_roles_weight_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-29,
  );
	//PR range settings
	$items['admin/config/camplus/pr_settings/range_settings'] = array(
		'title' => t('PR range settings'),
		'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_range_settings_form'),
    'access arguments' => array('access administration pages'),
		'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-27,
	);
  $items['admin/config/camplus/pr_settings/pr_approve_settings'] = array(
    'title' => t('PR approve workflow settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_approve_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-26,
  );
	return $items;
}

/**
 * Implements hook_permission().
 */
function camplus_pr_permission() {
	return array(
    'camplus purchase request approvable' =>  array(
      'title' => t('Camplus Purchase Request approvable'),//审批资格 权限
      'restrict access' => TRUE,
    ),
   );
}

/**
 * Implements hook_theme().
 */
function camplus_pr_theme() {
  return array(
    'camplus_pr_roles_weight_settings_form' => array(
      'render element' => 'form',
    ), 
    'camplus_pr_range_settings_form'  => array(
      'render element' => 'form',
    ),
    'camplus_pr_approve_settings_form'  => array(
      'render element' => 'form',
    ),            
  );
}
/**
 * Implements hook_form_alter().
 */
function camplus_pr_form_alter(&$form, &$form_state, $form_id) {
  $forms = array('camplus_pr_range_settings_form','camplus_pr_roles_involved_settings_form');
	if(in_array($form_id, $forms)){
    drupal_add_css(drupal_get_path('module', 'camplus_pr').'/camplus_pr.css');
  }
}

function camplus_pr_approve_flag_generate($key) {
  $flags = array();
  // Exported flag: "Bookmarks".
  $flags[$key] = array (
    'content_type' => 'node',
    'title' => 'Approve',
    'global' => '0',
    'types' => 
      array (
        0 => 'purchase_request',
      ),
    'flag_short' => 'Approve this PR',
    'flag_long' => 'Approve this Purchase Request',
    'flag_message' => 'This Purchase Request has been Approved',
    'unflag_short' => 'Unbookmark this',
    'unflag_long' => 'Remove this post from your bookmarks',
    'unflag_message' => 'This post has been removed from your bookmarks',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
      array (
        'flag' => 
        array (
          0 => 2,
        ),
        'unflag' => 
        array (
          0 => 2,
        ),
      ),
    'weight' => 0,
    'show_on_form' => 1,
    'access_author' => '',
    'show_on_page' => 1,
    'show_on_teaser' => 1,
    'show_contextual_link' => false,
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}