<?php

/**
 * Implements hook_node_view().
 */
function rate_pr_node_view($node, $view_mode, $langcode) {
  if ($view_mode != 'rss') {  
    // Adding the form to the node view
    $widgets = rate_get_active_widgets('node', $node->type, $view_mode);

  	_rate_pr_check_permissions($node, $widgets);

    foreach ($widgets as $widget_id => $widget) {
      if( $widget->name = 'approve') {
      	// 根据PR节点的总额确定which审批流程
      	// 在上一个审批流程没有确定前 其他后续

        $widget_name = 'rate_' . $widget->name;
        _rate_check_widget($widget);
        $display_mode = $view_mode == 'teaser' ? $widget->teaser_display_mode : $widget->node_display_mode;
        $widget_code = array(
          '#weight' => $widget->node_display == RATE_DISPLAY_ABOVE_CONTENT ? -50 : 50,
          '#markup' => rate_generate_widget($widget_id, 'node', $node->nid, $display_mode),
        );
        if ($widget->node_display == RATE_DISPLAY_DISABLE) {
          $node->$widget_name = $widget_code;
        }
        else {
          $node->content[$widget_name] = $widget_code;
        }
      }

    }
  }
}

function _rate_pr_check_permissions($node, $widgets, $user = NULL) {
	if(!_approve_rate_check($node, $user)) {
		//通过审批流程确定第X级用户，并确定权限
		$field_chosen_price = $node->field_chosen_price[LANGUAGE_NONE][0]['value'];
		$field_payment_from_students = $node->field_payment_from_students[LANGUAGE_NONE][0]['value'];
		$total = $field_chosen_price + $field_payment_from_students;
		// $count_rows =  variable_get('camplus_pr_settings_range', '5');
		// while ( $count_rows <=  1) {
		//  	$count_rows--;
		//  }
  	$camplus_pr_range_settings = variable_get('camplus_pr_range_settings');
  	dvm($total,'123');
  	$max = 0;
  	$i = 0;
  	dpm($camplus_pr_range_settings);
  	foreach ($camplus_pr_range_settings as $key => $value) {
  		if($value-$total >= 0) {
  			$temp = $key;
  			dpm($value-$total,$i);
  			// $max = $camplus_pr_range_settings[$key];
  			// dvm($key.'-'.$value);
  			break;
  		}
  		$i++;
  	}
	}else {
		return TRUE;
	}
}
//判断当前用户是否有权限 同意、拒绝
//判断当前用户是否投票了，即同意、拒绝了
//
//
/**
 * @return FALSE has no value in db,should check deep. 通过审批流程确定第X级用户，并确定权限
 * @return array() = TRUE. the current has right to approve/deny
 *	array(
 *	  'vote_id' => '10',
 *	  'entity_type' => 'node',
 *	  'entity_id' => '8',
 *	  'value' => '-1',
 *	  'value_type' => 'option',
 *	  'tag' => 'vote',
 *	  'uid' => '10',
 *	  'timestamp' => '1363945677',
 *	  'vote_source' => '127.0.0.1',
 *	)
 */
function _approve_rate_check($node, $user = NULL) {
	if(!$user) {
		global $user;
	}
	$result = db_select('votingapi_vote', 'v')
    ->fields('v')
    ->condition('entity_id', $node->nid)
    ->condition('uid',$user->uid)
    ->condition('value_type','option')

    ->execute()
    ->fetchAssoc();

	return $result;
}